### ISSUE TITLE
Error after flutter 3.0.0 update

### ISSUE THREAD

**Issue by turker2000** [paurakhsharma/flutter_chord#13]
Hi, After the Flutter 3.0.0 update, the following error message started to show. The application compiles but the error message keeps coming after each build.

Launching lib\main.dart on GM 5 Plus in debug mode...
Parameter format not correct -
√  Built build\app\outputs\flutter-apk\app-debug.apk.
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_chord-0.1.1/lib/src/lyrics_renderer.dart:159:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/C:/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.addPostFrameCallback((_) {
                   ^

**Comment by ShimronAlakkal** [comment]
This, probably, should be a problem with any old packages used in the project. Try updating every pub spec package to their latest versions. Seems like something of that sorts.

**Comment by turker2000** [comment]
All pubspec packages have been updated. the problem persists.

**Comment by alexaung** [comment]
It have to change in plugin not in your code. So wait for the update

**Comment by paurakhsharma** [comment]
Thank you for raising the issue. I have fixed it in version `0.1.2`. Feel free to re-open the issue if the problem persists.
