### ISSUE TITLE
User defined lyrics or url list

### ISSUE THREAD

**Issue by aresrana** [paurakhsharma/flutter_chord#15]
First of all, I would like to thank you for this package. I was searching for such since many weeks. Is there any way to accomplish this with the list of URL that we parse through firebase ? As of now looks like we need to define the same widget multiple times for multiple lyrics ?

**Comment by paurakhsharma** [comment]
We don't need to define the same widget multiple times. You can have a list of lyrics and map over it to display them individually or use `ListView`.

If you are having an issue with it please provide an example of what you have tried already.

If this is unclear feel free to open the issue again.
