### ISSUE TITLE
Intro Chords shown with space's

### ISSUE THREAD

**Issue by fadhly-permata** [paurakhsharma/flutter_chord#18]
Hi, @paurakhsharma .

Can you explain how to add some Chords Line without lyric?

For example:
```
Dear God - Avenged Sevenfold

[INTRO]
[F]  [C]  [Dm]  [Am]  [Bb]  [F]  [C]

"A[F] lonely [C]road, crossed[Dm] another cold sta[Am]te line..."
```

With format on above, i got result like this
```
Dear God - Avenged Sevenfold

INTRO
FCDmAmBbFC
 
 F        C             Dm                 Am
A lonely road, crossed another cold state line
```

As you can see, the output on intro part is not as i expected, What i need to do to get the result like below?
```
Dear God - Avenged Sevenfold

INTRO
F C Dm Am Bb F C
 
 F        C             Dm                 Am
A lonely road, crossed another cold state line
```

**Comment by fadhly-permata** [comment]
is this package discontinued and not maintained anymore?

**Comment by paurakhsharma** [comment]
Hey @fadhly-permata, sorry for late replay. 

Currently this packages doesn't support this, I will work on adding this support soon. 

For now you might need to add more spaces between the texts like this:
```
[F]    [C]    [Dm]        [Am]         [Bb]        [F]       [C]
```

**Comment by fadhly-permata** [comment]
It's ok for being slow resp, just feel wrong if I use not maintained version of packages.

> For now you might need to add more spaces between the texts like this:

Yes, I've tested it already, and it works. 

Thanks a lot for your response. I'll close this issue then

**Comment by fadhly-permata** [comment]
![image](https://user-images.githubusercontent.com/8925077/225235122-402e2582-c558-4821-813d-d771f699ddde.png)

FYI, sometime multiple space not working, as you can see on my screenshot

**Comment by paurakhsharma** [comment]
For chords with 2 or 3 characters more spaces are required.

**Comment by fadhly-permata** [comment]
As you can see on my screenshot, I am using 4 spaces (even though I've tried using tab or \t char) still not taking any effect. there is no difference between, 3, 4, 5, 6, 7, or 8 spaces

**Comment by fadhly-permata** [comment]
Oh another thing is.

May you add some interpreter for ChordPro or Ultimate Guitar format?

You can use my  simple logic from my post on StackOverflow: [https://stackoverflow.com/questions/75673904/get-chars-and-put-back-to-next-line](https://stackoverflow.com/questions/75673904/get-chars-and-put-back-to-next-line)

**Comment by paurakhsharma** [comment]
Ultimate Guitar format to Chord Pro format parser? Yes we can add it, please create a PR and may be add some tests for it.

**Comment by fadhly-permata** [comment]
> Ultimate Guitar format to Chord Pro format parser? 

Yes, I mean parser to convert from UG format to CP format.

OK, after I've done with my own project, I'll add the parser into flutter_chord. 

Thanks  a lot
