### ISSUE TITLE
Format verse number

### ISSUE THREAD

**Issue by jeremiahlukus** [paurakhsharma/flutter_chord#21]
Many of the songs i have are formatted with the verse number above the verse 

```
1
My first verse starts ...

2
my Sec verse starts..
```

I want to format them if present like in the screenshot. Would you be open to a PR for this? 

<img width="75" alt="Screenshot 2023-10-29 at 4 19 08 PM" src="https://github.com/paurakhsharma/flutter_chord/assets/17206638/1589f1e1-dae3-4852-ac71-6525a8be9fe4">

**Comment by jeremiahlukus** [comment]
Once i do this Ill start on https://github.com/paurakhsharma/flutter_chord/issues/17  if you are open for a PR. 

Ill also update the readme to include the supported directives (I should have did this in my last PR)

**Comment by paurakhsharma** [comment]
@jeremiahlukus Yes that would be cool, but please make it flexible for people to style it differently.

So it would be good to use directive for this as well so people are optionally opt it.

> {start_of_part:name} or {sop:name} - Indicates that a new section is starting, e.g. {sop:Verse 2}
{end_of_part} or {eop} - Indicates that a section has ended

I got this spec from: https://www.chordle.com/help/chordpro
