### ISSUE TITLE
Add chorus style to processLine

### ISSUE THREAD

**Issue by jeremiahlukus** [paurakhsharma/flutter_chord#25]
I did this on my fork 
https://github.com/jeremiahlukus/flutter_chord/commit/1fe5afb18d7dece2ca0c8dd3b5a4af7bc6c9b85d#diff-4e77cf45bdd4c26febea57be5f13f1605bb077a3fb163dbc259c7c5a08801819R146

The meat would be in `_processLine`

```
        final sizeOfLeadingLyrics = isChorus
            ? textWidth(_lyricsSoFar, chorusStyle)
            : textWidth(_lyricsSoFar, lyricsStyle);
```

When you have a chorus the text is thicker causing the chords to be off. 

If you give me permissions to branch ill send a PR. My fork is diverging a bit

**Comment by paurakhsharma** [comment]
Yes please send the PR for this I would be happy to merge it. Thank you.
