### ISSUE TITLE
Recommended Functions update

### ISSUE THREAD

**Issue by FlavioBarros13** [paurakhsharma/flutter_chord#4]
It’s a very powerful plug-in there are many in the community looking for something like it..since flutter is still expanding we don’t have it ..I’ve searched it for month’s till I found yours 

As a developer and musician great function to add would be:

- [x] Transpose for when changing the keys or chords of the song to a higher or lower ..it changes the scale

- [x] Auto roll down (like auto scrolling downwards )with speed function, this function is for when someone opens a song on the the app using the tablet or phone and he can press for  auto scroll while he’s playing and following the chords
Everything else is perfect so far..you did a great job..I even had to look for your contacts to congratulate you

**Comment by paurakhsharma** [comment]
Thank you so much @FlavioBarros13.

I will start working on these as soon as possible!

**Comment by Holid17** [comment]
You are amazing, I hope the latest update has a transpose feature and auto scroll speed control, thank you very much for making this plugin, very helpful, cheers

**Comment by paurakhsharma** [comment]
Thanks @Holid17, sorry not yet. I am still working on it. Got distracted with other stuff. Will complete is as soon as possible.

**Comment by paurakhsharma** [comment]
Just pushed `flutter_chord: 0.0.4`, which has these features :tada:

Let me know how it works for you. 

Fell free to re-open this issue or create new one it you need more tweaking with it.

Thank you.
