### ISSUE TITLE
text wrapping issue for base in apple's Myanmar language (Unicode)

### ISSUE THREAD

**Issue by alexaung** [paurakhsharma/flutter_chord#6]
My project is almost done. Listing Singer, Album and Song Track. Today I start rendering lyrics in LyricRenderer. It is working but I got 
    `A RenderFlex overflowed by 18 pixels on the right.`

If chord is near end of the right screen, that line give error. It should be wrapping base on word between space I guess. If there is no chord, word is going down but not by space.

If I can solved this issue by lyric and chord app is done :D

Please see the attached image.

![IMG_0001](https://user-images.githubusercontent.com/1129760/150867121-5f8d3467-5bbb-490b-b669-8387b407c3ab.PNG)

Key C Intro: Csus4 C Ceus4 

*[C]အမြန်လာပါ [Am7]အိမ်မက်ကလေးရေ [G]ဒီအချိန် 
[C]အပြင်မှာ [Am7]ရက်စက်တဲ့ညတွေ [F][G]မင်းရဲ့ကမ္ဘာမြေထဲ 
[E7]သူ့မျက်နှာ [Am]လေးအား [D7]ယူဆောင်ပေးပါ[G]လားကွာ[Em] 
[Dm7]ရင်မှာဒဏ်ရာ အို---ဝေးလွင့်သွာအောင် 

*[C]အမြန်လာပါ [Am7]အိမ်မက်ကလေးရေ [G]အရင်လို ငါဟာ[C] သူ့ရဲ့ [Am7]နှုတ်ခမ်းလေးတွေ [F][G]တမ်းတနေပြီလေ [Am] သူ့ရဲ့ [E7]အသံလေးများ [Am][D7]ပြန်လည်ကြားယောင်[G]တဲ့အခါ[Em] 
[Dm7]အိုးဝေးလွင့်သွားမယ့် အလွမ်းရဲ့ မီးလျှံများ(ဝေးလွင့်ရဲ့ အလွမ်းမီးလျှံများ) 

**[G][G]အပြင်ကမ္ဘာမှာ [Gm7]တို့နှစ်ယောက်[C7]ဝေးနေဆဲ [Bb]ဒါပေမယ့်[C]မင်းအရှေ့မှာ 
[F]ခဏလေးတွေ့ခွင့်ရ [Dm][G]ပြန်ဆုံပါရစေ [Em]အိမ်မက်လေးရေ [F]အိုး………….[G] 
Solo:  Am E7 Am D7 G Em Dm7(**) 

*[C]အမြန်လာပါ [Am7]အိမ်မက်ကလေးရေ
[G]ဒါဟာဒို့ရဲ့ [C]တကယ့်ဘဝလို [Am7]အမြဲတမ်းယုံကြည်တယ် 
[F][G]ရက်စက်ညများထဲ [Am]တစ်ခါပြန်မနိုးခင်အထိလေ[E7] [Dm7] 
*[Dm7] အိုးဝေးလွင့်သွားမယ့် အလွမ်းရဲ့ မီးလျှံများ (တမ်းတမိနေဆဲ) 
*[Dm7] အိုးဝေးလွင့်သွားမယ့် အလွမ်းရဲ့ မီးလျှံများ  
*[Dm7] တမ်းတမိနေဆဲ အိုဝေးလွှင့်သွားမယ့် (အလွမ်းရဲ့ မီးလျှံများ) 
*[Dm7](အို အမြဲတမ်းတနေဆဲ) (အိုဝေးလွင့်သွားမယ် အလွမ်းရဲ့မီးလျှံများ) 
*[Dm7](အို တမ်းတမိနေဆဲ)

**Comment by alexaung** [comment]
You can check with this one line

[G]ခေါင်းလောင်းလေးတွေမြည်နေပြီ [C]ငှက်ကလေးတွေလည်း တေးဆိုသည် [C]နာရီစင်ကသုံးချက် [G][G7]တီးသံမြည်

**Comment by alexaung** [comment]
any idea?

**Comment by auhsor** [comment]
I'm also interested in this one. I haven't had time to look through the code for a fix yet.

**Comment by paurakhsharma** [comment]
Hey, @alexaung thanks for opening the issue. I am still figuring out how to fix this.
If anyone wants to help please feel free to create a PR or suggest a solution.

**Comment by auhsor** [comment]
I've had a play with trying to fix it. It seems to work for me. #7

**Comment by paurakhsharma** [comment]
@alexaung Version `0.1.0` should fix this. Please try it and let us know. Thanks.

**Comment by paurakhsharma** [comment]
Closing this, for now, feel free to open it if it is not solved.
